LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ProxyPass /api/ http://backend:5000/
ProxyPassReverse /api/ http://backend:5000/

FallbackResource /index.html
