version: '3.8'

services:
  backend:
    build:
      context: ./backend
    expose:
      - "5000"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
